stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
  train_model:
    cmd: python src/train.py
    deps:
    - data/raw/train.csv
    - src/train.py
    outs:
    - models/model.pkl
